import { expect, test } from '@playwright/test';

test.use({ viewport: { width: 844, height: 390 }, hasTouch: true });

test('mobile HUD buttons, pointer input, menu and responsive layout', async ({ page }, info) => {
  test.setTimeout(60000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('./?mobile=1');
  const surface = page.locator('[data-phase]');
  await expect(surface).toHaveAttribute('data-phase', 'ready');
  expect((await page.locator('.guide').boundingBox())!.height).toBe(80);
  await expect(page.locator('.cue > span').first()).toBeHidden();
  await expect(page.locator('.game-input-mask')).toHaveCount(1);
  await expect(page.locator('.touch-controls')).toHaveAttribute('data-icon-mode', 'video');
  await expect(page.getByRole('button', { name: '회피', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: '연습 시작', exact: true }).tap();
  await expect(surface).toHaveAttribute('data-phase', 'running');
  await page.getByRole('button', { name: '회피', exact: true }).tap();
  await expect(surface).toHaveAttribute('data-last-input-time', /\d/);
  await expect(page.locator('.video-progress')).toHaveCount(0);
  await expect(page.locator('.touch-action.is-pressed')).toHaveCount(0);
  // Real canvas pixels must be populated from the video, not a blank placeholder.
  const pixels = await page.locator('.touch-action canvas').first().evaluate((canvas: HTMLCanvasElement) =>
    [...canvas.getContext('2d')!.getImageData(0, 0, canvas.width, canvas.height).data].filter((_, i) => i % 4 === 3).some(a => a > 0));
  expect(pixels).toBe(true);
  await page.waitForFunction(() => document.querySelector('video')!.currentTime > 1.4);
  await page.screenshot({ path: info.outputPath('landscape-live.png') });
  await page.getByRole('button', { name: '제어 메뉴 열기' }).tap();
  await expect(surface).toHaveAttribute('data-phase', 'paused');
  await page.getByRole('button', { name: /인게임 입력 가리기/ }).tap();
  await expect(page.locator('.touch-controls')).toHaveAttribute('data-icon-mode', 'fixed');
  await expect(page.locator('.touch-controls canvas')).toHaveCount(0);
  await page.getByRole('button', { name: '제어 메뉴 닫기' }).tap();
  await page.getByRole('button', { name: '이어서 하기', exact: true }).tap();
  await expect(surface).toHaveAttribute('data-phase', 'running');
  await page.getByRole('button', { name: '리듬 바 접기' }).tap();
  const inputBox = (await page.locator('.touch-controls').boundingBox())!;
  const expandBox = (await page.getByRole('button', { name: '리듬 바 펼치기' }).boundingBox())!;
  const expandedVideo = (await page.locator('.video-stage').boundingBox())!;
  expect(expandBox.x).toBeCloseTo(expandedVideo.x + expandedVideo.width, 0);
  expect(expandBox.y + expandBox.height).toBeCloseTo(expandedVideo.y + expandedVideo.height, 0);
  expect(expandBox.x).toBeGreaterThanOrEqual(inputBox.x + inputBox.width);
  await page.screenshot({ path: info.outputPath('landscape-fixed-expanded.png') });
  await page.getByRole('button', { name: '리듬 바 펼치기' }).tap();
  await page.setViewportSize({ width: 667, height: 375 });
  await page.screenshot({ path: info.outputPath('landscape-small.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  const videoBox = (await page.locator('.video-stage').boundingBox())!;
  const portraitPad = (await page.locator('.touch-controls').boundingBox())!;
  expect(portraitPad.y).toBeGreaterThanOrEqual(videoBox.y + videoBox.height - 1);
  await page.screenshot({ path: info.outputPath('portrait.png') });
  await page.getByRole('button', { name: '리듬 바 접기' }).tap();
  const portraitExpand = (await page.getByRole('button', { name: '리듬 바 펼치기' }).boundingBox())!;
  const foldedPad = (await page.locator('.touch-controls').boundingBox())!;
  expect(portraitExpand.x).toBeGreaterThanOrEqual(foldedPad.x + foldedPad.width);
  await page.getByRole('button', { name: '지원', exact: true }).tap();
  await expect(page.locator('.guide')).toHaveCount(0);
  await page.getByRole('button', { name: '리듬 바 펼치기' }).tap();
  await page.setViewportSize({ width: 844, height: 390 });
  await expect(surface).toHaveAttribute('data-phase', 'finished', { timeout: 25000 });
  await expect(page.locator('.touch-controls')).toHaveCount(0);
  expect(await page.locator('.result-header').evaluate(el => el.getBoundingClientRect().height)).toBe(1);
  await expect(page.locator('.result-key-label small').first()).toBeHidden();
  await expect(page.getByRole('button', { name: '다시 연습', exact: true })).toBeInViewport();
  const resultBox = (await page.locator('.results').boundingBox())!;
  const coverBox = (await page.locator('.video-cover').boundingBox())!;
  expect(resultBox.height).toBeLessThan(175);
  expect(coverBox.y + coverBox.height).toBeCloseTo(resultBox.y, 0);
  const restart = page.getByRole('button', { name: '다시 연습', exact: true });
  const restartBox = await restart.boundingBox();
  await page.screenshot({ path: info.outputPath('results.png') });
  await page.locator('.result-cue').first().tap();
  await expect(page.locator('.result-detail')).toBeVisible();
  expect(await restart.boundingBox()).toEqual(restartBox);
  await page.screenshot({ path: info.outputPath('results-detail.png') });
  await page.locator('.result-cue').first().tap();
  await expect(page.getByRole('button', { name: '입력 선택으로', exact: true })).toBeInViewport();
  await page.getByRole('button', { name: '다시 연습', exact: true }).tap();
  await expect(surface).toHaveAttribute('data-phase', 'running');
  expect(errors).toEqual([]);
});

test('compact preparation guide retains route hints and full icons', async ({ page }, info) => {
  await page.goto('./?mobile=1');
  await expect(page.locator('[data-phase]')).toHaveAttribute('data-phase', 'ready');
  await page.getByRole('button', { name: '제어 메뉴 열기' }).tap();
  await page.getByRole('combobox', { name: '보스', exact: true }).selectOption('larval');
  await expect(page.locator('[data-phase]')).toHaveAttribute('data-phase', 'ready');
  await page.getByRole('button', { name: '제어 메뉴 닫기' }).tap();
  expect((await page.locator('.guide').boundingBox())!.height).toBe(96);
  await expect(page.locator('.preparation-note')).toBeVisible();
  await expect(page.locator('.preparation-dodge kbd').first()).toBeHidden();
  expect(await page.locator('.cue-symbol').first().evaluate(el => el.getBoundingClientRect().height)).toBe(34);
  await page.getByRole('button', { name: '연습 시작', exact: true }).tap();
  await expect(page.locator('[data-phase]')).toHaveAttribute('data-phase', 'running');
  await page.screenshot({ path: info.outputPath('compact-preparation.png') });
});
