import { expect, test } from '@playwright/test';
import { writeFileSync } from 'node:fs';

test('practice layout: anchored results, edge controls, and floating original menu', async ({ page }, info) => {
  test.setTimeout(80_000);
  await page.setViewportSize({width:1280,height:720});
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('./');
  const surface = page.getByRole('region',{name:'연습 입력 영역'});
  await expect(surface).toHaveAttribute('data-phase','ready');
  const geometry = async () => page.evaluate(() => {
    const box = (s: string) => {
      const el = document.querySelector(s); if(!el) return null;
      const r = el.getBoundingClientRect(); return {x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom};
    };
    return {video:box('.video-stage'),guide:box('.guide'),result:box('.results'),workspace:box('.practice-workspace'),
      controls:box('.cover-actions'), title:box('.cover-title'), entry:box('.entry-selection'),
      scroll:document.querySelector('.practice-scroll')!.scrollTop};
  });
  const ready = await geometry();
  expect(ready.guide!.bottom).toBeCloseTo(720,0);
  await page.screenshot({path:info.outputPath('01-ready.png')});
  const collapse = page.getByRole('button',{name:'리듬 바 접기',exact:true});
  const c = (await collapse.boundingBox())!;
  expect(c.x).toBeCloseTo(ready.guide!.x + ready.guide!.width,0);
  expect(c.height).toBeCloseTo(118,0);
  await collapse.click();
  await expect(page.locator('.guide')).toHaveCount(0);
  const collapsed = await geometry();
  expect(collapsed.video!.height).toBeGreaterThan(ready.video!.height);
  await page.screenshot({path:info.outputPath('02-collapsed.png')});
  await page.getByRole('button',{name:'리듬 바 펼치기',exact:true}).click();
  const trigger = (await page.getByRole('button',{name:'제어 메뉴 열기'}).boundingBox())!;
  expect(trigger.width).toBe(1280);
  expect(trigger.height).toBe(await page.locator('.masthead').evaluate(el => (el as HTMLElement).offsetHeight));
  await page.mouse.move(8, trigger.height - 2);
  await expect(page.locator('.header-shell')).toHaveClass(/is-floating/);
  expect((await geometry()).scroll).toBeCloseTo(ready.scroll,0);
  expect((await geometry()).video!.y).toBeCloseTo(ready.video!.y,0);
  await expect(page.locator('.masthead')).toHaveCount(1);
  await page.screenshot({path:info.outputPath('03-floating-menu.png')});
  await page.mouse.move(640,400);
  await expect(page.locator('.header-shell')).not.toHaveClass(/is-floating/);
  await page.getByRole('button',{name:'연습 시작',exact:true}).click();
  await expect(surface).toHaveAttribute('data-phase','running');
  await page.waitForFunction(() => document.querySelector('video')!.currentTime > .4);
  await page.getByRole('button',{name:'일시정지',exact:true}).click();
  await expect(surface).toHaveAttribute('data-phase','paused');
  await page.getByRole('button',{name:'이어서 하기',exact:true}).click();
  await expect(surface).toHaveAttribute('data-phase','running');
  const t = await page.locator('video').evaluate((v: HTMLVideoElement) => v.currentTime);
  await collapse.click();
  await expect(surface).toHaveAttribute('data-phase','running');
  await expect(surface).toBeFocused();
  await expect(surface).not.toHaveAttribute('data-last-input-time');
  expect(await page.locator('video').evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThanOrEqual(t);
  await page.getByRole('button',{name:'리듬 바 펼치기',exact:true}).click();
  await expect(surface).toHaveAttribute('data-phase','finished',{timeout:20000});
  const finished = await geometry();
  expect(finished.result!.bottom).toBeCloseTo(ready.guide!.bottom,0);
  expect(finished.video).toEqual(ready.video);
  expect(finished.result!.y).toBeLessThan(finished.video!.bottom);
  await page.screenshot({path:info.outputPath('04-results.png')});
  await page.locator('.result-cue').first().click();
  await page.waitForTimeout(100);
  const detail = await geometry();
  expect(detail.result!.bottom).toBeCloseTo(ready.guide!.bottom,0);
  expect(detail.video).toEqual(ready.video);
  expect(detail.controls).toEqual(finished.controls);
  expect(detail.title).toEqual(finished.title);
  expect(detail.entry).toEqual(finished.entry);
  expect(detail.result!.y).toBeLessThan(finished.result!.y);
  await page.screenshot({path:info.outputPath('05-result-detail.png')});
  await page.locator('.result-cue').first().click();
  await expect(page.locator('.result-detail')).toHaveCount(0);
  expect((await geometry()).controls).toEqual(finished.controls);
  await page.locator('.result-cue').first().click();
  const resized=[];
  for(const size of [{width:1366,height:768},{width:800,height:600},{width:390,height:844}]){
    await page.setViewportSize(size); await page.waitForTimeout(200);
    const g=await geometry(); resized.push(g);
    expect(g.result!.bottom).toBeCloseTo(size.height,0);
    expect(g.video!.bottom).toBeCloseTo(size.height - 118,0);
    await page.screenshot({path:info.outputPath(`06-detail-${size.width}.png`)});
  }
  expect(errors).toEqual([]);
  writeFileSync(info.outputPath('layout.json'),JSON.stringify({ready,collapsed,finished,detail,resized},null,2));
});

test('menu remains usable with keyboard, scroll, and Mirage controls', async ({page},info) => {
  await page.setViewportSize({width:1280,height:720});
  await page.goto('./');
  await expect(page.locator('[data-phase]')).toHaveAttribute('data-phase','ready');
  await page.getByRole('button',{name:'제어 메뉴 열기'}).focus();
  const boss=page.getByRole('combobox',{name:'보스',exact:true});
  await expect(boss).toBeFocused();
  await page.mouse.move(600,400);
  await page.waitForTimeout(450);
  await expect(page.locator('.header-shell')).toHaveClass(/is-floating/);
  await boss.selectOption('mirage-archer-unit');
  await expect(page.locator('[data-phase]')).toHaveAttribute('data-phase','ready');
  await page.mouse.move(640,2);
  await expect(page.locator('.header-shell')).toHaveClass(/is-floating/);
  await page.getByRole('combobox',{name:'tile type',exact:true}).selectOption('overlap');
  await expect(page.locator('[data-phase]')).toHaveAttribute('data-phase','ready');
  await page.mouse.move(640,2);
  await expect(page.locator('.header-shell')).toHaveClass(/is-floating/);
  await page.screenshot({path:info.outputPath('mirage-floating.png')});
  expect(await page.locator('.masthead').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.getByRole('button',{name:'레인 아이콘 표시'}).focus();
  await page.keyboard.press('Escape');
  await expect(page.locator('.header-shell')).not.toHaveClass(/is-floating/);
  await page.mouse.move(640,400);
  await page.mouse.wheel(0,-800);
  await expect.poll(async()=>page.locator('.practice-scroll').evaluate(e=>e.scrollTop)).toBe(0);
  await expect(boss).toBeInViewport();
  await expect(page.locator('.header-shell')).not.toHaveClass(/is-floating/);
  await page.mouse.wheel(0,800);
  await expect(page.getByRole('button',{name:'제어 메뉴 열기'})).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(200);
  const edge=(await page.getByRole('button',{name:'리듬 바 접기',exact:true}).boundingBox())!;
  expect(edge.x+edge.width).toBeLessThanOrEqual(390);
  await page.screenshot({path:info.outputPath('narrow-ready.png')});
});
